### PR TITLE
Write tests for wrapper

### PR DESCRIPTION
**Pull request by tvararu**
Previously https://github.com/alphagov/accessible-typeahead/pull/50.

### CODE REVIEW

**Comment by tvararu** [comment]
@nickcolley I decided to leave the `setTimeout` hack in because in the future I'd like to write our tests with Jest so we can use [timer mocks](https://facebook.github.io/jest/docs/en/timer-mocks.html#content).

**Comment by nickcolley** [comment]
Are you sure we want these tests if we have your new e2e tests?

**Comment by tvararu** [comment]
@nickcolley Yes, they are faster. The end to end tests are mainly responsible for keeping a finger on multi-browser support.

**Comment by tvararu** [comment]
Thanks again for your contribution @nickcolley. 👍

**Comment by nickcolley** [comment]
image

**Pull request merged**
