### PR TITLE
Rename component to accessible-autocomplete

### LINKED ISSUE #66: Change project name from typeahead to autocomplete
We recently decided to refer to this as an autocomplete rather than a typeahead. Autocomplete felt more natural and appears to be in more common usage (comparing similar components and search terms).

To do:
* Change repo name
* Change readme docs
* Change internal references

### PR DESCRIPTION
**Pull request by tvararu**
Closes #66.

- [x] Update references in README
- [x] Update references in `accessibility-criteria.md`
- [x] Update references in src
- [x] Update references in test
- [x] Update references in examples
- [x] Update references in BEM CSS [Breaking]
- [x] Update references in package.json
- [x] Update references in webpack
- [x] Update references in app.json
- [x] Update references in CONTRIBUTING
- [x] Rebuild dist, remove old ones
- [x] Update GitHub description
- [x] Update CHANGELOG
- [ ] Rename GitHub repository
- [ ] Update GitHub website URL
- [ ] Create new minor version
- [ ] Publish new NPM package
- [ ] Make sure Travis still works
- [ ] Make sure Coveralls still works
- [ ] Make sure unpkg still works
- [ ] Make sure Sauce Labs still works
- [ ] Make sure version badge still works
- [ ] Make sure gzip size still works
- [ ] Make sure Heroku still works
- [ ] Update `openregister-location-picker` to use new one
- [ ] Deprecate old NPM package

### CODE REVIEW

**Comment by tvararu** [comment]
```bash
$ grep -ir "typeahead" dist/
$ grep -ir "typeahead" examples/
$ grep -ir "typeahead" src/
$ grep -ir "typeahead" test/
$ grep -i "typeahead" *.*
CHANGELOG.md:- [Breaking] Rename component from `accessible-typeahead` to `accessible-autocomplete`.
CHANGELOG.md:- Test the typeahead with end to end tests.
CHANGELOG.md:- [Breaking] Rename `dist/styled.min.css` to `dist/accessible-typeahead.min.css`.
CHANGELOG.md:- [Breaking] Rename library main export from `AccessibleTypeahead` to `accessibleTypeahead`.
CHANGELOG.md:- Add `AccessibleTypeahead.enhanceSelectElement` function.
CHANGELOG.md:- Turn off native browser autocomplete so it doesn't interfere with typeahead overlay.
CHANGELOG.md:- [Breaking] Change the CSS classes to our own instead of the jQuery typeahead ones.
CHANGELOG.md:- Don't specify typeahead menu width inline. Allows custom CSS to override it.
package.json:    "typeahead",
README.md:Similar to the [`source` argument for typeahead.js](https://github.com/corejavascript/typeahead.js/blob/47d46b40cb834d8285ac9328c4b436e5eccf7197/doc/jquery_typeahead.md#datasets), a backing data source for suggestions. `query` is what gets typed into the input field, which will callback to `populateResults` synchronously with the array of string results to display in the menu.
README.md:- [corejavascript/corejs-typeahead](https://github.com/corejavascript/typeahead.js): flexible autocomplete/suggestion engine architecture
```

The last references are in the CHANGELOG, the `package.json` search keywords, and the README when referencing other packages that really are called `*-typeahead`. These are all fine.

**Comment by nickcolley** [comment]
image
made you a logo

**Comment by tvararu** [comment]
@nickcolley that looks sick

@edwardhorsford what do you think?

**Comment by nickcolley** [comment]
We could also have vans

image

**Pull request merged**
